### ISSUE TITLE
Highlight elements in the completion

### ISSUE THREAD

**Issue by andreabrambilla** [equinor/esv-intersection#103]
It should be possible to highlight selected elements in the completion layer (programmatically). 
One example application is highlighting the element that is hovered by the mouse 

Depends on #8,

technically, this would relate to #75. The goal is to create a separate layer for event listeners

**Comment by thuve** [comment]
This story should also include the tooltip.

**Comment by Juan-MM** [comment]
Will be covered later. Closing.
