### ISSUE TITLE
Some clarification about the the Reference Frame

### ISSUE THREAD

**Issue by andreabrambilla** [equinor/esv-intersection#128]
@Brynjulf @HavardNJ @stalenestas 

I have spent some time trying to wrap my head around why we need to have the transformation available inside the intersection component.

We are dealing with a transformation from a 2D space (the _curtain_ in 3D) to another 2D space (a flat plane). In the general case, such a transformation can introduce distortions, so that the (geodesic) distance between two points in one space is not the same in the other space. And even worse, the distortions could change across the space, so some areas are more distorted than others. In these situations you need to be able to back-project points from the flat plan to the curtain in order to correctly measure lengths (or, do local approximations using the metric tensor). So, yes, in the general case, we need to have the transformation available in the intersection. 

However, that applies to the general case. In our case, the transformation _should_ be isometric, ie, that should be no distortions in length and areas (the metric tensor is an identity everywhere). A displacement on the plane should correspond 1 to 1 to a displacement on the curtain. I think the curtain analogy is particularly fitting: if you take a curtain and lay it flat on the floor, the size of the curtain does not change.

What still change are angles, which affects normals and tangents (as Håvard pointed out), and curvature tensors. But are we actually using these in the intersection component?

**Comment by miwegmann** [comment]
As I understood it from @HavardNJ , the re-calculation of normals and tangents is needed e.g. when the size of casing needs to be exaggerated due to the small casing diametres compared to the very long well paths. And I guess this is happening several times when zooming in and out.

**Comment by andreabrambilla** [comment]
I thought that completions, casing etc etc, are given in terms of MD and diameter. In that's the case, MD grows linearly along the well-path both in the 3D and the projected 2D space (once again, flattening a curve does not change the size of the curtain). And the diameter can be taken into account as an offset orthogonal to the well-path in the projected space. 

I guess that exaggerating the scale of casings/completion can be accomplished by including a multiplicative constant for the diameter, there should be no need to take the original transformation into account.

IF we need the original normals of the curtain, or the normal/binormal/tangent of the well-path (Frenet frame), then yes, we need to have the transformation available. But I still can't understand why we would need that data

I assume the transformation is used in the current intersection implementation in REP, if someone could point out where to look at, I could look at the code myself and try to figure it out

**Comment by NibeGH** [comment]
Delete issue. Now closed
