### ISSUE TITLE
Rename webgl-layer to pixilayer

### ISSUE THREAD

**Issue by HavardNJ** [equinor/esv-intersection#129]
Rename the webGL layer to pixi layer to make it more clear what technology is being use as pixi may or may not use webGL. Currently force canvas is set which means it's not using webGL, this options should be exposed to the user of the layer in the layer options.

**Comment by stalenestas** [comment]
I think this is a option I forgot to remove when we decided to not go down the legacy-pixi path of supporting both.
Pixi v5 lost the canvas possibility, and most of what is done currently in the hole/casing layers requires webgl regarding the textures.
