### ISSUE TITLE
Fixed label layer

### ISSUE THREAD

**Issue by jgvabo** [equinor/esv-intersection#14]
The component must allow for fixed labels to annotate e.g. directions (NW - SW) and axis properties and dimensions.

**Comment by farzadfz** [comment]
This is a basic functionality that goes together with the axis

**Comment by andreabrambilla** [comment]
directional labels should be always visible (in front of any other layer) and unaffected by zoom and panning

**Comment by andreabrambilla** [comment]
There is already a working implementation in REP, it should be revised and ported to this repo
