### ISSUE TITLE
Discussion: how to serve real data from the hosted stories

### ISSUE THREAD

**Issue by Brynjulf** [equinor/esv-intersection#140]
We cannot take the volve data directly into the stories, so we need to find a good way to include it in the hosted stories on radix

**Comment by Brynjulf** [comment]
one suggestion is that we can create a repo and deploy that repo privately on equinor's npm and fetch the data from there.

**Comment by Brynjulf** [comment]
another is to connect to a storage to get the data

**Comment by Brynjulf** [comment]
you could also fetch data directly from a github repo using github's api (v3)

**Comment by andreabrambilla** [comment]
Commenting on the first suggestion (but valid in general), the repo does not need to be private, the license for the volve license allows us to host it publicly, as long as we use the same license (ie, a modified version of creative commons)

I was wondering, the "test data" that you and Håvard are using, how big is it?

**Comment by Brynjulf** [comment]
one set is 8.8 mb, where the seismic data takes up about 4.5mb, and casing takes about 3.6mb

**Comment by Brynjulf** [comment]
solution going forward is to have an open repo in github where we serve the volve data from, will need to confirm that authentication is not required for accessing files there
