### ISSUE TITLE
Reference lines for RKB, MSL and Seabed

### ISSUE THREAD

**Issue by miwegmann** [equinor/esv-intersection#163]
REP (current) has extra lines indicating sea level (dashed blue) and depth ref (dashed gray). Should be added to next as well.

Lines to support: 
- Blue wavy line for MSL
- RKB
- Seabed

Depths should be configurable.

![rkb-msl-intersection.png](https://images.zenhubusercontent.com/5db9383b6670a40001ae1b21/41cdff16-7b5d-4365-bcaa-d3e58709c8da
)

REP has a working implementation here https://github.com/equinor/mad-project-rep/blob/dev/src/components/intersection/SeaAndRKBLayer.js 

Consider implementing with optional number of lines, and everything configurable for each line. Something like 
`data: { lineType: 'wavy' | 'solid', color: string, text: string, depth: number }[]`

**Comment by andreabrambilla** [comment]
@HavardNJ can you confirm that this has been done? thanks!

**Comment by Brynjulf** [comment]
@andreabrambilla this has been done on the REP side, it is currently a separate layer. But we wanted to merge the highlighting (red dot) with the sea level and depth ref. lines into one layer. short answer, it has been done, just not added to this repo

**Comment by Juan-MM** [comment]
Same as #151

**Comment by NibeGH** [comment]
Look into this later this year (Spring / Summer 2022)
Re to issue:

**Comment by HavardNJ** [comment]
@equinor/wellx-dev Any interest in having this layer in the component? There is an implementation in /src/components/intersection/SeaAndRKBLayer.js in REP

**Comment by ooystein** [comment]
Yes, there is an interest in this layer. https://github.com/equinor/mad-project-rep/blob/dev/src/components/intersection/SeaAndRKBLayer.js seems like a complete and fairly self contained implementation of this. Can we have a chat about getting it in to esv-intersection @HavardNJ?

**Comment by HavardNJ** [comment]
IMHO this could simply be lifted from REP into the component (maybe cleaned up a bit).
