### ISSUE TITLE
Improve performance of seismic layer

### ISSUE THREAD

**Issue by andreabrambilla** [equinor/esv-intersection#187]
The current implementation of the seismic layer does not allow the user to change the color scale dynamically

Reimplement it so that it gets fast enough. Håvard mentioned he will try out implementations based on Pixi and Webassembly (the former is probably more suitable, the latter would reduce dependencies and solve the issue of the GL contexts, see #159)

**Comment by andreabrambilla** [comment]
This issue, plus #186 and #188 will be first investigated in REP

**Comment by HavardNJ** [comment]
Will be handled in REP eventually, closing here
