### ISSUE TITLE
deploy component to github registry

### ISSUE THREAD

**Issue by Brynjulf** [equinor/esv-intersection#195]
whenever we release, we should deploy to both npm and github

**Comment by Brynjulf** [comment]
Currently there is no easy way of installing packages that are only available in npm (and not github), and any fixes that are implemented here would only resurface when the people next in line want to deploy their own package. That's why we are holding off on deploying to github while github/npm offer up a proper solution to this.

**Comment by venikx** [comment]
Not sure if I understand the blocking part, but for the lithology-patterns repo we both publish to npm and private github repo. 

See: https://github.com/equinor/lithology-patterns/blob/main/.github/workflows/publish-npm.yml

**Comment by HavardNJ** [comment]
Not sure I understand either, I'll leave this for Brynjulf once he's back

**Comment by venikx** [comment]
Closing as it now should be handled with: https://github.com/equinor/esv-intersection/blob/59198e296162f8636a9effd2c1e64c8b0e3380c9/.github/workflows/release.yml#L37
