### ISSUE TITLE
Intersect more than one wellbore

### ISSUE THREAD

**Issue by jgvabo** [equinor/esv-intersection#20]
Not pt. a feature in REP, but useful to consider when rewriting.

It would be useful if the component could display an intersection of two wells or more wells, and the path between them.

**Comment by andreabrambilla** [comment]
This can be a bit complex, need further investigation
We need some illustrations about what this is supposed to look like before moving forward

**Comment by NibeGH** [comment]
Originally a request from the REP team. 
Arrange meeting with REP team to finalise if this and other issues conc REP are still relevant.

**Comment by HavardNJ** [comment]
Backlog in REP, closing
