### ISSUE TITLE
Add cement and casing data to data repo

### ISSUE THREAD

**Issue by andreabrambilla** [equinor/esv-intersection#200]
Generate the dataset starting from real data from CSD and randomly modify it a bit

**Comment by stalenestas** [comment]
CSD is still missing Volve data. Andreas will check with someone who might know where it is.

**Comment by thuve** [comment]
@stalenestas The volve wells have been marked as "expired" in CSD. To me as a user I can view the data by toggling the "expired" button in the top left corner in explorer. Don't know if that helps for retrieving data? 
![volve data in csd](https://user-images.githubusercontent.com/32099492/81924239-29d08b00-95df-11ea-91de-d6748a1cd0b1.jpg)
