### ISSUE TITLE
Feature: Investigate scaling for completion items, tiny cement width

### ISSUE THREAD

**Issue by stalenestas** [equinor/esv-intersection#217]
The scaling for the completion items is possibly off. Difficult to see the cement between casing and hole when the casing/hole is small

**Comment by andreabrambilla** [comment]
Support dynamic scaling, where everything along the well is scaled orthogonally to the well depending on the zoom level

On top of that, allow to pass in a global scaling factor that is multiplied with the dynamic scaling

There is some code in REP for this but it is probably a bit ugly

**Comment by ovineq** [comment]
Closing this, referenced issue is closed.
