### ISSUE TITLE
Revise the content and the structure of the storybook

### ISSUE THREAD

**Issue by andreabrambilla** [equinor/esv-intersection#227]
Got some feedback that the storybook is really difficult to use in its current state.
There are a number of improvement that we should consider, including:
- using realistic data in the Intersection story
- revise the classification used for grouping story (currently some classes are technical, eg Pixi layers, some classes are semantic, ie Axis

See also #118

**Comment by andreabrambilla** [comment]
Here is my suggestion:
```
1. Features
  - Axes
  - Grid
  - Geomodel
  - Callout
  - Wellbore
  - Wellbore with Callouts
  - Hole, Casing and Cement
  - ... etc etc
2. Complete example
  - Intersection
3. Other examples
  - Data conversion
  - Intersection with arbitrary curve (no well)
  - Intersection with vertical well
  - Anything else that may be useful
```

Basic requirements:
- Each and every of the layers we provide must have one dedicated entry in the `Features` section. If reasonable, it can appear in more than one entry (eg, Hole, Casing, and Cement should each have their own entry, but it makes sense to have an entry with all of them together)
- Each and every of the layers we provide must be part of the Complete Example, and should be toggle-able
- The `Other examples` should show _useful_ or _interesting_ usages of the component, no specific requirement here

@HavardNJ @Brynjulf @stalenestas any comment?

**Comment by Brynjulf** [comment]
Yeah that could work, I also think that for each we should include a high level and low level example, ie with and without using the controller.

**Comment by Brynjulf** [comment]
Depending on how we fetch data, should we also have two separate stories: one fetching real data (where applicable) and one using mocked data?

**Comment by andreabrambilla** [comment]
I'm not entirely sure. I mean, it can be useful, but retrieving the data is something that belongs to the application using the component, not to the component itself. We can use one method (eg, fetching from git) as the default one across the storybook, and have a story int the "Other examples" section where we get the data in a different way

**Comment by Brynjulf** [comment]
It would be a moot point if we can simply put the data inside storybook, because my reasoning for it was mainly so that at least one example would always be consistent (ref. request limit on github api)
