### ISSUE TITLE
Hitting Github API rate-limiting on storybook

### ISSUE THREAD

**Issue by ooystein** [equinor/esv-intersection#265]
When debugging in the storybook locally (and probably in the deployed version to radix also) I quickly hit the Github API rate limit. 

Do you have a way of working locally that don't pull the esv-intersection-data from github?
If not, would you consider adding a flag or some way to get the app to work without hitting Github while developing?

**Comment by Brynjulf** [comment]
Hi @ooystein, we recently merged a pull request for this (#258 ), in the file `.storybook/src/api/index.ts` there is a commented line that will export mock data.

**Comment by ooystein** [comment]
The mock data from apiMock.ts seems to be lacking. It makes it very hard to create a bug report when I cant create edit the mock data or the mock data is not available. Any suggestions? Maybe you have a clever way I haven't tried.

**Comment by Brynjulf** [comment]
@ooystein , it is true, we are lacking in proper mocked data. Could you elaborate when you say you can't edit the mock data?

We do have to revise how we fetch data and serve it to storybook or any other hosted demos

**Comment by ooystein** [comment]
I'm trying to make a branch to reproduce a bug. To demonstrate the bug I need to have some mock data. And easiest way would be if I could edit the mock data the repository already is using. But when the mockdata is lacking, and the good mock data from esv-intersection-data is unavailable due to github api rate limiting it's hard to cobble together an example.

**Comment by Brynjulf** [comment]
@ooystein in order to edit the mock data and stage the changes you would need to remove the line `./storybook/src/exampledata/**` from the gitignore file

**Comment by Brynjulf** [comment]
we are using the data repo as a submodule, so this is no longer an issue
