### ISSUE TITLE
The Ekofisk label in the Storybook flies around

### ISSUE THREAD

**Issue by andreabrambilla** [equinor/esv-intersection#284]
In the Intersection story in the storybook, the Ekofisk label seems to follow around when zooming and panning up and down, instead of staying within the boundaries of the formation (probably the dark blue one)

**Comment by HavardNJ** [comment]
Same bug in REP in prod, I'll look into it. Kind of have a feeling there is something odd with the data.

**Comment by HavardNJ** [comment]
Due to how the base for ekofisk is found. I've changed the logic to use nearest instead of "best". This may have implications for how surfaces are displayed in REP, but I have not found any wellbores with issues yet. But this does need some extensive testing in REP.

**Comment by HavardNJ** [comment]
Old issue where some work was done, not seeing issue now so closing
