### ISSUE TITLE
Duplicate GeomodelLayer

### ISSUE THREAD

**Issue by andreabrambilla** [equinor/esv-intersection#293]
We have 2 implementations of the GeomodelLayer, let's just merge them into a single one

**Comment by ooystein** [comment]
The two GeomodelLayer seems to have the same API and generate about the same render result. GeomodelLayerV2 is refactored and seems the better of the two.

Can we delete GeomodelLayer and rename GeomodelLayerV2 to GeomodelLayer?
If we care for not breaking that API we can keep the GeomodelLayerV2 name by extending GeomodelLayer until we can deprecate that layer.

**Comment by andreabrambilla** [comment]
@HavardNJ
