### ISSUE TITLE
Enhance cement pattern resolution and change pattern

### ISSUE THREAD

**Issue by thuve** [equinor/esv-intersection#299]
Increase the resolution of the cement pattern. Today, it becomes very pixelated at high zoom level. 

Also render the cement pattern with a constant angle relative to the wellbore path. (As it is now, If the well path has an equal angle as the cement pattern, then the pattern will run parallel)

Example of constant relative cement angle

![image](https://user-images.githubusercontent.com/32099492/83648661-97585180-a5b6-11ea-8cc5-7742162cf4bb.png)

**Comment by ooystein** [comment]
"Constant relative cement angle" is fixed.

"Cement pattern becomes very pixelated at high zoom level." remains a issue. This should be tackled after we have decided on how to fix zFactor warping on well layers and decided if we should switch well layers to SVG or Canvas Layer.

**Comment by schoening** [comment]
Closing. Will be requested again if feature is still relevant.
