### ISSUE TITLE
Include rendering of "sub casing"

### ISSUE THREAD

**Issue by thuve** [equinor/esv-intersection#301]
The casing layer should support rendering of a casing string with diameter variations. A typical example would be an intermediate 10 3/4" x 9 5/8" casing, where the top part is 10 3/4" and the bottom is 9 5/8". 

The image below shows an example of how it is today. There's a diameter variation in the casing from the designer, but this does not show up i the intersection. 
![image](https://user-images.githubusercontent.com/32099492/83727208-fe244c00-a644-11ea-87fa-09ca88874fd6.png)

Here's how it should approximately look like (include the closed end rendering):
![image](https://user-images.githubusercontent.com/32099492/83727670-b8b44e80-a645-11ea-8243-2bf5ce4e9a2c.png)

**Comment by andreabrambilla** [comment]
@ooystein @Brynjulf was this ever fixed? If not, do we have some data we can use to create a dedicated story in the storybook?

**Comment by Brynjulf** [comment]
![Screenshot 2020-09-11 at 15 07 31](https://user-images.githubusercontent.com/6473221/92929947-a8302300-f441-11ea-8384-30d9cd166299.png)

I'm not sure if its the order of the data or the rendering that is causing smaller casings to overlay the larger casings, but you do have overlap for casing with the closed end rendering.

**Comment by ooystein** [comment]
No, this was postponed to first fix the other rendering issues we had. I forgot all about it. We will put it in our todo!

> I'm not sure if its the order of the data or the rendering that is causing smaller casings to overlay the larger casings, but you do have overlap for casing with the closed end rendering.

Casings can overlap and I think this is correct. But we need to support casings with varying diameter.
