### ISSUE TITLE
Create a Storybook entry with data from POZO

### ISSUE THREAD

**Issue by andreabrambilla** [equinor/esv-intersection#328]
Håvard and I have the intersection.json file to try this out.
Note that the file cannot be published because the data is confidential, we would have to create an analogous file for showing this in the public storybook

**Comment by miwegmann** [comment]
Still tbd discussed how the data is supposed to look like ("mangled") when put to the storybook. Start with testing on locally stored data.

**Comment by schoening** [comment]
Closing. Will be requested again if the documentation for this is still relevant.
