### ISSUE TITLE
Move the Storybook to Github pages

### ISSUE THREAD

**Issue by andreabrambilla** [equinor/esv-intersection#337]
This is only a suggestion, not sure if it's appropriate, nor if it's feasible (we already have the documentation on github pages, right?).

Since Radix will become a paid service from August, using github pages would avoid any discussion about what WBS to use (even though the amount will be negligible)

If this is too much work, we can find an agreement on what WBS to use

**Comment by Brynjulf** [comment]
remember to update the repo's link in the about section of this repo to point to github pages and not radix
