### ISSUE TITLE
Investigate graceful fallback when WebGL is not available

### ISSUE THREAD

**Issue by andreabrambilla** [equinor/esv-intersection#341]
This is currently being investigated in REP, let's wait until that investigation is completed, then we can apply the same approach in this component

**Comment by ooystein** [comment]
We have tested to use Pixi.js-legacy that provides fallback for when WebGL is not available in the browser. We did not notice any performance difference in the non WebGL browser.

To use Pixi.js-legacy the consuming app replaces the peer dependency Pixi.js with Pixi.js-legacy when bundling or load it as a standalone library in the app. The legacy version of Pixi.js checks if WebGL is available before it turns on legacy mode, so the applications does not need to have two different builds for different browser capabilities.

There is nothing that needs to be done in this library to allow the fallback, but maybe it could be documented in the README.
