### ISSUE TITLE
ReferenceSystem can produce non-monotonic paths even though the input is monothonic

### ISSUE THREAD

**Issue by andreabrambilla** [equinor/esv-intersection#347]
**Describe the bug**
We are still working on prducing a small example to reproduce the issue. 
In short, there are certain paths with points have monotonically increasing TVD, but some the reference system can produce oscillations given certain values of MD. 
The rendering for holes/casing/cement relies on the reference system for computing primitives, and when this issue occurs, visual artifacts are produced.

We believe the reason behind this is that we rely on the CurveInterpolator for mapping across reference frames. While the curve interpolator is handy in setting up this mapping, it also applies a catmull rom interpolation, which is not necessarily what we want here. We have noticed that setting `tension = 1` (thus reducing catmull rom to a simpler interpolation scheme) solve the problem. We may need a discussion about this, but for the needs required by the ReferenceSystem, a simple linear interpolation may be more suitable
 

**To Reproduce**
We will post some data for this, or maybe create a dedicated test

**Expected behavior**
No oscillation should be produced as a consequence of the interpolation

**Screenshots**
Coming soon

**Desktop (please complete the following information):**
Not related to the system or browser, we could reproduce the issue even in the console

**Additional context**
Nothing to report

@ooystein

**Comment by ooystein** [comment]
I have created a test to demonstrate what we are seeing here:
https://github.com/ooystein/esv-intersection/commit/89083cbee5e62a057dd49a27b2d5f8ab1f8686d9

**Comment by schoening** [comment]
Closing. Will be requested again if still relevant.
