### ISSUE TITLE
GeomodelLayer lines distort when increasing zFactor

### ISSUE THREAD

**Issue by ooystein** [equinor/esv-intersection#359]
See how a GeomodelLayer line is distorted when zFactor is increase. The line
 should have uniform thickness. 

![original-line](https://user-images.githubusercontent.com/705469/92903071-1369fd00-f422-11ea-932c-278c6d549e45.png)

**Comment by ooystein** [comment]
I have a suggested fix in #360
It makes the line uniform, but the line thickness is not configurable by the user. The thickens is always 1px no mather what the data says. 
Is the configurable thicknes of the lines a feature that is needed? If so we need to look for another solution.

Attached a image of how it looks with this patch applied.

![zFactor-10](https://user-images.githubusercontent.com/705469/92903750-9a1eda00-f422-11ea-867f-63e67ff5977e.png)

**Comment by Brynjulf** [comment]
I'm not actually sure if we have a need to exaggerate lines in the geomodel layer, @farzadfz do you have any insight into the usability of this?

**Comment by farzadfz** [comment]
@Brynjulf If we are looking at depth surfaces, the line thickness does not represent any physical feature. It is only important that the surface is visible in different zoom and scale factor settings. Does that clarify?

**Comment by ooystein** [comment]
Ok. Then I will remove the configurable thicknes for lines in GeomodelLayers and submit PR for review.
