### ISSUE TITLE
User should be able to toggle on and off different layers

### ISSUE THREAD

**Issue by andreabrambilla** [equinor/esv-intersection#36]

**Comment by andreabrambilla** [comment]
The component itself should support both hiding (stuff is rendered but not displayed) and entirely disabling (no rendering occurs, data ignored) a layer.
UI for toggling on and off belongs to the application using the component, we could make a very simple interface just for testing purposes (eg, https://wellx.equinor.com/demo/ )

**Comment by SvSven** [comment]
Argument for not including UI elements for toggling and such is that this will be integrated into different systems that each have their own styles and behaviours for UI elements such as dropdowns, checkboxes, toggles, etc - for example WellCom uses their own unique styling and behaviour and wants this to be consistent throughout the application.
