### ISSUE TITLE
Possible bug in Wellborepath layer

### ISSUE THREAD

**Issue by andreabrambilla** [equinor/esv-intersection#362]
Part 1: In the "Highlight wellborepath" story in the storybook, the highlighted point is reset when you pan & zoom. To reproduce:
- Open the story https://equinor.github.io/esv-intersection/storybook/master/?path=/story/features--highlight-wellborepath
- move the slider so that the highlighted point is moved to a location different from the well start
- pan the view with the mouse
-> the highlighted point is moved back at the beginning of the well

Part 2: In the story "Highlight wellborepath with Controller" the highlighted point does not match the position of the slider. If you start moving the slider from left to right, the following happens:
- in the first part, the slider moves but the highlighted point does not move
- then the highlighted point starts moving with the slider
- once the highlighted point reaches the end of the wellbore path, the slider is not at the right end yet. Moving the slider in the remaining area does not affect the highlighted point

**Comment by nicholasdalhaug** [comment]
Hi! Is it okay if I work on this?

**Comment by schoening** [comment]
Closing. Fixed.
