### ISSUE TITLE
Failing tests for getExtendedTrajectory

### ISSUE THREAD

**Issue by ooystein** [equinor/esv-intersection#383]
See branch with enabled tests for getExtendedTrajectory: https://github.com/equinor/esv-intersection/tree/getExtendedTrajectory-issue

**getExtendedTrajectory()**
- returns an end extension that is shorter than requested
- difference in distance between points are too big according to test. The difference might be acceptable but then the tests need to be updated accordingly.

**Comment by schoening** [comment]
Closing.
