### ISSUE TITLE
Add section in contribution file about how deployment is done

### ISSUE THREAD

**Issue by Brynjulf** [equinor/esv-intersection#384]
Should include an entry in the `contribution.md` about how deployments are triggered and what happens

**Comment by venikx** [comment]
I've automated to release workflow even further with the help of https://github.com/changesets/changesets. If you like a certain change to bump the version in a certain way, you can run `changeset` in your command line and go through the prompts. 

Once the PR or commit (including the changeset generated markdown file) lands in the main branch, the `changeset/action` create a release PR (see: https://github.com/equinor/esv-intersection/pull/624). 
Once esv-intersection is ready to be released, this PR can be merged and it will automatically create Github release notes, update the changelog, publish to NPM and publish to Github registry.

**Comment by venikx** [comment]
Added how to release and deploy new version here: https://github.com/equinor/esv-intersection/commit/daca20cb76345e34aac272cef6708815e28cbefa
