### ISSUE TITLE
Invert isLeftToRight in CalloutCanvasLayer

### ISSUE THREAD

**Issue by ooystein** [equinor/esv-intersection#389]
- Invert isLeftToRight in CalloutCanvasLayer when calculateDisplacementFromBottom == true.

- Check if other layers calculates a isLeftToRight and need fix.

This is how picks collide now for wells with displacement calculated from bottom.
![picks collision](https://user-images.githubusercontent.com/705469/98348820-84402680-2019-11eb-9258-3c8c38cfb932.png)

Here is an example when isLeftToRight is negated: 
![picks collision fixed](https://user-images.githubusercontent.com/705469/98348831-8609ea00-2019-11eb-9681-c6e9b01b12a2.png)

Need to implement negation when IntersectionReferenceSystem.options.calculateDisplacementFromBottom == true.
https://github.com/equinor/esv-intersection/blob/5851be8c0316d36e72e803bead3e57f72ca5a778/src/layers/CalloutCanvasLayer.ts#L94.

**Comment by tormy** [comment]
This solved it for me:
`const isLeftToRight = this.options.referenceSystem.options.calculateDisplacementFromBottom ? xBounds[0] < xBounds[1] : xBounds[0] > xBounds[1];`

**Comment by ooystein** [comment]
We should check and fix if GeomodelLabelsLayer and other layers has any isLeftToRight check.
