### ISSUE TITLE
Duplicate options in multiple layers

### ISSUE THREAD

**Issue by HavardNJ** [equinor/esv-intersection#393]
F.ex.
"'options' is defined as an accessor in class 'PixiLayer', but is overridden here in 'GeomodelLayerV2' as an instance property."
This is an issue in multiple layers

**Comment by ooystein** [comment]
Pointed out by @tormy in Pozo also. I'll see if I get time to fix this tomorrow.

**Comment by ooystein** [comment]
Last options accessor overriden in sub classes fixed in https://github.com/equinor/esv-intersection/pull/424
