### ISSUE TITLE
Render tubing in intersection component

### ISSUE THREAD

**Issue by nilsml** [equinor/esv-intersection#452]

**Comment by ooystein** [comment]
Implementation is ready to be verified by @NibeGH 
Steps to view tubing in intersection:
1. Go to  https://wellx-designer.app.radix.equinor.com/
2. Delete bottom casing
3. Drag tubing symbol from toolbox and drop on bottom hole
4. See tubing rendered with linear gradient in esv-intersection component

**Comment by NibeGH** [comment]
Tubing successfully drops in both well log and intersection.
Only issue is tubing does not fit hole size width. Assume dialogue box will ensure correct dimension goes in?
![image.png](https://images.zenhubusercontent.com/613b37d3a639047b513b6140/7edc6541-2dd1-4ce5-9003-dedd231647be)

**Comment by ovineq** [comment]
You're correct @NibeGH. In the quick design one should be able to specify the dimensions and the designer will respect them.
I'll remove the random dimensions from the demo. 👍🏻

**Comment by ovineq** [comment]
Updated in last PR:
![image](https://user-images.githubusercontent.com/91891939/140297525-030c2b17-e6d4-43b3-933e-9f4e4d50fac5.png)

**Comment by NibeGH** [comment]
Looks good. Can I close now?

**Comment by ovineq** [comment]
I merged the PR for removing the random dimensions of tubing in the demo.
You can close this one now. 👍🏻
