### ISSUE TITLE
Render straddle in esv-intersection

### ISSUE THREAD

**Issue by ovineq** [equinor/esv-intersection#459]
Support for straddle [is implemented in wellx-wellog](https://github.com/equinor/wellx-wellog/issues/57).

We'll start off with a new layer in esv-intersection for image-based components.

Here is a image of a straddle in well-log, the visuals of the plug should be the same in esv-intersection.

![image.png](https://images.zenhubusercontent.com/615c2d2bc862bebc44e526aa/ea9813d9-710b-4f42-b63e-bf89ac07f9c9)

**Comment by ovineq** [comment]
Implemented through [`PAndASymbol`](https://github.com/equinor/esv-intersection/blob/85dbf76c85b8c3b69f4ae2ae7459261bd2ea656d/src/layers/schematicInterfaces.ts#L35)

**Comment by ovineq** [comment]
Testing:
Should appear in the same way as in the well schematic, and moving the straddle in the well schematic should move it in intersection.

**Comment by NibeGH** [comment]
Looks good. Please proceed.
