### ISSUE TITLE
Render mechanical plug in esv-intersection

### ISSUE THREAD

**Issue by nilsml** [equinor/esv-intersection#461]
@ooystein commented on [Fri Jun 11 2021](https://github.com/equinor/wellx-designer/issues/288)

Support for mechanical plug is implemented in wellx-wellog and wellx-designer.

See description o[f task for implementing mechanical plug in well-log](https://github.com/equinor/wellx-wellog/issues/56), might have overlapping information.

This might need a new layer in esv-intersection inheriting from WellboreBaseComponentLayer for P&A components.

Here is a image of a mechanical plug in well-log, the visuals of the plug should be the same in esv-intersection.

![image.png](https://images.zenhubusercontent.com/60d07c95af69b15e69a791e9/4138fb11-9434-454d-88f5-6a4e525cb2b5)

**Comment by ovineq** [comment]
Implemented through [`PAndASymbol`](https://github.com/equinor/esv-intersection/blob/85dbf76c85b8c3b69f4ae2ae7459261bd2ea656d/src/layers/schematicInterfaces.ts#L35)

**Comment by ovineq** [comment]
Testing:
Should appear in the same way as in the well schematic, and moving the mechplug in the well schematic should move the plug in intersection.

**Comment by NibeGH** [comment]
Looks good. Please proceed
