### ISSUE TITLE
Excess CPU load by Pixi.js Layers

### ISSUE THREAD

**Issue by ooystein** [equinor/esv-intersection#473]
When running intersection component with PIXI layers computer CPU load is quite high, even when user is not interacting with the component.

The excess load seems to stem from Pixi.Application game loop rerendering the Pixi layers on every requestAnimationFrame. It seems fairly straight forward to implement our own render controller to trigger rendering only on data updates and zoom/pan interactions by users.

**Comment by ovineq** [comment]
Related CPU improvement work: `stop PIXI requestAnimationFrame render loop` https://github.com/equinor/esv-intersection/pull/475

**Comment by ooystein** [comment]
Solved by https://github.com/equinor/esv-intersection/pull/475
