### ISSUE TITLE
Cement squeeze in esv-intersection

### ISSUE THREAD

**Issue by ooystein** [equinor/esv-intersection#482]
Render cement squeeze. (Might be same as normal casing cement but with different color)
![image.png](https://images.zenhubusercontent.com/5db9383b6670a40001ae1b21/d6ade283-007d-4b6c-b1b2-14038412e74f
)

**Comment by schoening** [comment]
Currently in discussions with @ovineq and @ooystein about re-implementing layer visibility logic (currently using 'internalLayers')

**Comment by ooystein** [comment]
To fully test this we need to update wellx-designer to send cement squeeze data to intersection component. Will update issue when it's ready for acceptance.

**Comment by NibeGH** [comment]
Looks good. Please proceed.
