### ISSUE TITLE
Whipstock in esv-intersection

### ISSUE THREAD

**Issue by ooystein** [equinor/esv-intersection#483]
Add blue triangel to represent whipstock. 
![image.png](https://images.zenhubusercontent.com/5db9383b6670a40001ae1b21/fbafadc1-db50-4571-858c-0bb6225272d4)

**Comment by ovineq** [comment]
We'll use the [plug and abandonment image](https://github.com/equinor/esv-intersection/blob/85c13e791fc125e9134438d85103aeca6b8faf95/src/layers/schematicInterfaces.ts#L33) symbols for this feature.

**Comment by NibeGH** [comment]
Looks good. Please proceed @ooystein @ovineq
