### ISSUE TITLE
Perforation in esv-intersection

### ISSUE THREAD

**Issue by ooystein** [equinor/esv-intersection#484]
Previous discovery: https://github.com/equinor/wellx-designer/issues/222#issuecomment-1168775693
Perforations visualization: https://drillingandwellsolutions.atlassian.net/browse/CSD-199

Perforations should render after holes/casings, but before completion and P&A according to: https://github.com/equinor/wellx-designer/issues/703#issuecomment-1231716659

**Comment by schoening** [comment]
@NibeGH 
Currently there are still some rendering artifacts (spikes that get cut off) when drawing the perforation over multiple different types of Perforations and over different diameters.
I would like to know if this is ok or if I should spend some time at removing these:
![image.png](https://images.zenhubusercontent.com/61e6bca1fe61d44e4645f4a0/7cad4a40-6755-4ea3-8595-2bf9b0032893)
![image.png](https://images.zenhubusercontent.com/61e6bca1fe61d44e4645f4a0/1630cb87-7b45-4500-a235-a5afc5ba6bdc)

**Comment by NibeGH** [comment]
Lets proceed and see what it looks like in demo @schoening
