### ISSUE TITLE
Perforation + Cased hole fracturation: Should color the perforation spikes yellow

### ISSUE THREAD

**Issue by ovineq** [equinor/esv-intersection#542]
**Perforation + Cased hole fracturation:**
QD & P/SC:
![image.png](https://images.zenhubusercontent.com/615c2d2bc862bebc44e526aa/75c01dbe-9e0d-4f94-9dcf-4404c3c76926)

Interactive:
![image.png](https://images.zenhubusercontent.com/615c2d2bc862bebc44e526aa/b5d0f33d-297a-4932-ad8b-b06167182fc6)

**Comment by venikx** [comment]
- needs to have a rule that makes sure perforation cased hole becomes yellow

**Comment by NibeGH** [comment]
Look ok in test but i think still too large. Can discuss at next stand up @venikx ![image.png](https://images.zenhubusercontent.com/613b37d3a639047b513b6140/661ca0d8-fb88-415d-afc7-a790459d1290)

**Comment by venikx** [comment]
They just got merged, not sure if it automatically updates it to dev/qa. If they are still too large with real world data we can adjust in a later release.

**Comment by NibeGH** [comment]
Update still not visible in dev or qa @venikx

**Comment by NibeGH** [comment]
Update still not visible in dev or qa @venikx
