### ISSUE TITLE
Custom icon/symbol layer to display custom events and items along the wellbore

### ISSUE THREAD

**Issue by farzadfz** [equinor/esv-intersection#58]
The component should be able to display custom icon/symbols along the well path. This icons and symbols can represent different events or equipment (that are not part of the completion) alonge the well. 
Example of equipment: radio active sources in the well, fish, etc.
Example of events along the well: mud loss, collision, out of reservoir

![image](https://user-images.githubusercontent.com/43919188/73768195-e57c5600-4778-11ea-91e3-9ba80e69554f.png)

If this is covered by #11 or should be merged with it, that it can be dropped.

**Comment by andreabrambilla** [comment]
Let's start doing this as an "Other example" in the storybook

**Comment by NibeGH** [comment]
Originally a request from the REP team.
Arrange meeting with REP team to finalise if this and other issues conc REP are still relevant.

**Comment by HavardNJ** [comment]
Implemented in REP, closing
