### ISSUE TITLE
Log overlay in intersection view

### ISSUE THREAD

**Issue by farzadfz** [equinor/esv-intersection#60]
The component should have a well log layer where logs can be displayed as:

1. A curve/well log track where well path (with a possible offset) is the primary axis.  
2. "Cylinder log" where values of the log along the wellbore are displayed by colors. It can be continuous or discrete. 

Input to this layer are logs represented as depth(md)-value pair and a color coding scheme.
This will provide the users a spatial understanding when looking at the log
![image](https://user-images.githubusercontent.com/43919188/73868997-c7caf180-4849-11ea-9b59-d6fe4b02be1c.png)

**Comment by andreabrambilla** [comment]
When this will be addressed, please splkit it in two separate issues, one for the color coding, one for the plots

**Comment by NibeGH** [comment]
Originally a request from the REP team.
Arrange meeting with REP team to finalise if this and other issues conc REP are still relevant.

**Comment by HavardNJ** [comment]
Backlog in REP, closing
