### ISSUE TITLE
Tessellation layer

### ISSUE THREAD

**Issue by andreabrambilla** [equinor/esv-intersection#74]
Expose a semantically meaningful abstract API for providing data and converts it to polygons, that can be passed on to the Geomodel Layer

**Comment by HavardNJ** [comment]
Added functions in datautils to generate trajectory(needed to generate surface data) and surface data from data from SDMA. Trajectory could possibly be moved to separate repository as its used in several repositories (Intersection, REP and REP Client API, but may be relevant for others as well).
