### ISSUE TITLE
Completion schematic layer (generic version)

### ISSUE THREAD

**Issue by jgvabo** [equinor/esv-intersection#8]
# Completion & casing schematic layer
The component should have a completion & casing schematic layer.

Should be able to highlight key items with colors (e.g. using regexp matching).

Should get a tooltip with more info about the component on mouse over.

**Comment by andreabrambilla** [comment]
As a first version we will draw completion elements as _generic_, ie everything has the same shape

Later on we can assign different shapes to the different kind of elements
