### ISSUE TITLE
Zoom and panning controlled programmatically

### ISSUE THREAD

**Issue by andreabrambilla** [equinor/esv-intersection#81]
As a developer using the intersection component, I want to be able to control the zoom level and the panning offset programmatically. Also, I'd like to be notified when the zoom and panning are changed in the Intersection component

**Comment by HavardNJ** [comment]
Programmatic control of zoom and pan is demonstrated by the center and reset buttons in the zoom storybook. Notifications for changes in zoom is available through callback:
new ZoomPanHandler(root, (event: OnUpdateEvent) => {
    // Handle changes to zoom and pan here
  });
