### ISSUE TITLE
Snyk: esv-intersection - October 2024

### ISSUE THREAD

**Issue by GuillaumeVix** [equinor/esv-intersection#859]
## Description
Recurring task to fix esv-intersection vulnerabilities.

Have a look at the equinor/esv-intersection [vulnearibilities](https://app.snyk.io/org/videx/projects?groupBy=targets&before&after&searchQuery=&sortBy=highest+severity&filters[Show]=&filters[Integrations]=&filters[CollectionIds]=)

- [package.json](https://app.snyk.io/org/videx/project/00f225a2-6115-4e79-a942-cb14dcf86be8)
- [Code Analysis](https://app.snyk.io/org/videx/project/17ca0f71-579c-4bd5-861b-ae638a64dbed)

![Image](https://github.com/user-attachments/assets/ebc032ea-9d04-4ba0-96b4-505aec6356c1)

## How to test
Repository equinor/esv-intersection [vulnearibilities](https://app.snyk.io/org/videx/projects?groupBy=targets&before&after&searchQuery=&sortBy=highest+severity&filters[Show]=&filters[Integrations]=&filters[CollectionIds]=) should not have vulnerabilities equal or above 'Medium'.

## Acceptance criteria
1. esv-intersection repository does not have any detected vulnerability equal or above 'High' ('medium' and 'low' are discarded)
2. Clean-up no longer relevant PR from Snyk and dependabot

**Comment by VRiveland** [comment]
Adding the version of esv-intersection with the snyk updates to rep through this PR https://github.com/equinor/mad-project-rep/pull/5907

**Comment by ezarubina** [comment]
Waiting for merging [#5907](https://github.com/equinor/mad-project-rep/pull/5907)

**Comment by VRiveland** [comment]
> Waiting for merging [#5907](https://github.com/equinor/mad-project-rep/pull/5907)

#5907 is now merged :)
