### ISSUE TITLE
Verify if example from `react-intersection-example` should be ported to `esv-intersection`

### ISSUE THREAD

**Issue by GuillaumeVix** [equinor/esv-intersection#860]
## Description
Verify if some of the example in the repository https://github.com/equinor/react-intersection-example should be ported to https://github.com/equinor/esv-intersection

Remark: we are not expecting it, but would like to double-check before deleting the repository `react-intersection-example`.

## Acceptance criteria

1. If an example present in `react-intersection-example` is missing in `esv-intersection` and would add information, port it to `esv-intersection`

**Comment by VRiveland** [comment]
It was a bit of a struggle getting the example to run. Once I did get it to run, this was the only content in the entire intersection example repo:
![Image](https://github.com/user-attachments/assets/e0dafc9e-378f-4d40-9acb-247aefd484af)

We do not need to update the storybook in the esv-intersection repo, as we alsready have a story that shows a zoomable grid with axis.
