### ISSUE TITLE
Pixmap (seismic) layer

### ISSUE THREAD

**Issue by jgvabo** [equinor/esv-intersection#9]
# Pixmap layer
Should be able to display a pixmap layer. Will be used for e.g. seismic. Colorscale should be configurable.

**Comment by farzadfz** [comment]
This is an essential layer when looking at subsurface data. Very essential for REP and most probably for POZO and WELLCOM

**Comment by HavardNJ** [comment]
We currently have a pixmap layer and a seismic layer. Utils for creating an image from seismic data is provided, this does take a colorscale as a parameter. IMHO creating something generic which takes a set of data and convert it to an image using a color scale should be up to the application.
