### ISSUE TITLE
Show new features when they are available

### ISSUE THREAD

**Issue by Brynjulf** [equinor/esv-intersection#91]
Do not cache index.html to always fetch the newest changes made to the hosted site

**Comment by andreabrambilla** [comment]
@Brynjulf please double check if this is still an issue. If so, I guess this is a quick fix, right?

**Comment by Brynjulf** [comment]
@andreabrambilla this is still an issue, but yes it should be an easy fix of twaking the nginx config file

**Comment by andreabrambilla** [comment]
Part of #227

**Comment by NibeGH** [comment]
Originally a request from the REP team.
Arrange meeting with REP team to finalise if this and other issues conc REP are still relevant.

**Comment by HavardNJ** [comment]
Leaving this for now until Brynjulf is back if it's  indeed a small change to a config file

**Comment by venikx** [comment]
Closing as with Github Pages you can't control caching behaviours, and caching is only set to 10 minutes I believe. 
See: https://github.com/equinor/esv-intersection/commit/74b8e097c43a8bea1abd0fd0f4a98ed5f016c08d
